sudo: required
services:
  - docker

before_install:
  - docker build -t doodlehaus/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true doodlehaus/react-test npm test

after_success:
  - docker build -t doodlehaus/multi-client ./client
  - docker build -t doodlehaus/multi-nginx ./nginx
  - docker build -t doodlehaus/multi-server ./server
  - docker build -t doodlehaus/multi-worker ./worker
  # Log into docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push doodlehaus/multi-client:latest
  - docker push doodlehaus/multi-nginx:latest
  - docker push doodlehaus/multi-server:latest
  - docker push doodlehaus/multi-worker:latest
